[project]
name = "weeb-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cachetools>=7.1.6",
    "google-genai>=2.15.0",
    "httpx[http2]>=0.28.1",
    "img2pdf>=0.6.3",
    "pydantic>=2.13.4",
    "selectolax>=0.4.11",
    "tenacity>=9.1.4",
    "ua-generator>=2.1.2",
]
